# Generated by Django 3.2.7 on 2021-09-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='FileDescriptor_name',
            new_name='first_name',
        ),
    ]
